[env]
LANG = "en_US.UTF-8"

[window]
padding = { x = 10, y = 10 }
dynamic_title = true

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
size = 16.0

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
  { key = "W", mods = "Command", action = "None" },
]
